export enum QueryKey {
  AvailableVaults = 'availableVaults',
  Vault = 'vault',
  TrustScoreDetails = 'trustScoreDetails',
  TokenPrice = 'tokenPrice',
  UserBalance = 'userBalance',
  RefCode = 'refCode',
  DashboardStats = 'dashboardStats',
  DashboardHistory = 'dashboardHistory',
  VaultsCount = 'vaultsCount',
  VaultFee = 'vaultFee',

  MyVaults = 'myVaults',
  CybroBalance = 'CybroBalance',
  ClaimedCybroBalance = 'ClaimedCybroBalance',
  AvailableRewards = 'availableRewards',
  StakedReport = 'stakedReport',
  TotalStaked = 'totalStaked',
  Notifications = 'notifications',
  NotificationSettings = 'notificationSettings',
  FundHistories = 'fundHistories',

  ExchangePool = 'ExchangePool',
  BalanceErc20 = 'BalanceErc20',
  CybroRate = 'CybroRate',
  CybroPrice = 'CybroPrice',
  SeasonalVaultChart = 'seasonalVaultChart',

  TokenList = 'tokenList',
  StakedAmount = 'stakedAmount',
}
